import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { graph } from "../src/agent/turn_graph/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "../.docs/graphs");

mkdirSync(outDir, { recursive: true });

const INTERNAL_NODES = new Set(["__start__", "__end__"]);
const CUSTOM_KEYS: Array<"isLlm" | "purpose" | "characteristics" | "inputs" | "outputs"> = [
  "isLlm",
  "purpose",
  "characteristics",
  "inputs",
  "outputs",
];

type NodeMeta = {
  purpose?: string;
  characteristics?: string;
  inputs?: string;
  outputs?: string;
  isLlm?: boolean;
};

// getGraph() returns shared references to the builder's nodeSpec.metadata objects.
// Save the custom metadata into a separate map first, then clone+strip the shared
// objects so Mermaid node labels only show __interrupt.
const drawable = graph.getGraph();

const savedMeta = new Map<string, NodeMeta>();
for (const [id, node] of Object.entries(drawable.nodes)) {
  if (INTERNAL_NODES.has(id) || !node.metadata) continue;
  savedMeta.set(id, {
    isLlm: node.metadata.isLlm as boolean | undefined,
    purpose: node.metadata.purpose as string | undefined,
    characteristics: node.metadata.characteristics as string | undefined,
    inputs: node.metadata.inputs as string | undefined,
    outputs: node.metadata.outputs as string | undefined,
  });
  // Clone before stripping so the original builder metadata is untouched
  node.metadata = { ...node.metadata };
  for (const key of CUSTOM_KEYS) delete node.metadata[key];
}

// Annotate each node label with its LLM status.
// LangGraph emits lines like: \tnode_id(label_text) or \tnode_id(label_text):::class
const mermaid = drawable.drawMermaid().replace(
  /(\t)([\w]+)\(([^)]*)\)(:::[\w]+)?/g,
  (match, tab, nodeId, label, cssClass) => {
    const meta = savedMeta.get(nodeId);
    if (!meta || meta.isLlm === undefined) return match;
    const indicator = meta.isLlm ? "🤖 LLM" : "⚙️ logic";
    return `${tab}${nodeId}(${label}<br/><small>${indicator}</small>)${cssClass ?? ""}`;
  }
);

// --- Nodes section ---

const nodeIds = Object.keys(drawable.nodes).filter((id) => !INTERNAL_NODES.has(id));

const nodesSection = nodeIds
  .map((id) => {
    const meta = savedMeta.get(id) ?? {};
    const lines: string[] = [`### \`${id}\``];
    if (meta.purpose) lines.push(`\n**Purpose:** ${meta.purpose}`);
    if (meta.characteristics) lines.push(`\n${meta.characteristics}`);
    if (meta.inputs) lines.push(`\n**Inputs:** ${meta.inputs}`);
    if (meta.outputs) lines.push(`\n**Outputs:** ${meta.outputs}`);
    return lines.join("\n");
  })
  .join("\n\n---\n\n");

// --- Output ---

const output = `# MooGPT — LangGraph Diagram

> Auto-generated by \`npm run update:graph\`. Do not edit manually.

## Graph

\`\`\`mermaid
${mermaid}
\`\`\`

---

## Nodes

${nodesSection}
`;

const outPath = join(outDir, "turn_graph.md");
writeFileSync(outPath, output, "utf-8");
console.log(`Written: ${outPath}`);
